### ISSUE TITLE
citar-denote-subdir needs a slash for denote-directory

### ISSUE THREAD

**Issue by apraga** [pprevos/citar-denote#47]
Hi,

On my configuration with doom-emacs, I have to add a slash at the beginning of `citar-denote-subdir` as https://github.com/pprevos/citar-denote/blob/47f1ed2fbdd6ce88e65dd5ec77e984dfa4f72d49/citar-denote.el#L495 does not concatenate directories properly.

Can you confirm ?

Thanks

My config for reference 
```lisp
;; Bibliography managed by denote in a subdirectory
(after! citar
  :config
  (setq! citar-bibliography '("~/org/biblio/main.bib")))

(use-package citar-denote
  :ensure t
  :after (:any citar denote)
  :custom
  ;; Package defaults
  (citar-denote-subdir "/biblio") ; Bug , no slash appended
  (citar-denote-title-format "author-year")
  :config
  (citar-denote-mode)
  )

```

**Comment by pprevos** [comment]
Hi, I updated the code that generates the directory. It should work now independently of whether you have a trailing or starting slash in either variables. Commit: [4ae054c](https://github.com/pprevos/citar-denote/commit/4ae054c1a5f723bb4e8ffedeb59e0cfd3803f776)

**Comment by apraga** [comment]
Thanks for the super quick fix ! 
I've tested with `emacs -q -l test/init.el` on HEAD but the issue still persists on my side unfortunately.

**Comment by pprevos** [comment]
What is the value of these variables in your config:

- `denote-directory`
- `citar-denote-subdir`

The code that determined the note's location is:

```lisp
(when citar-denote-subdir
     (if (stringp citar-denote-subdir)
         (expand-file-name denote-directory citar-denote-subdir)
       (denote-subdirectory-prompt)))
```

Something is not quite right in this logic.

**Comment by apraga** [comment]
In your test/init.el, the values are changed to 
```lisp
  (denote-directory "~/org/zk")
  (citar-denote-subdir "biblio")
```
The subdirectory does exist. With the latest version, adding slashes does not seems to work anymore.

Could this work ?
```lisp
(file-name-concat denote-directory citar-denote-subdir)
```

**Comment by pprevos** [comment]
Oops, I revered the parameters. I should have tested more.

'''lisp
(setq denote-directory "~/org/zk")
(setq citar-denote-subdir "biblio")
(when citar-denote-subdir
     (if (stringp citar-denote-subdir)
         (expand-file-name citar-denote-subdir denote-directory)
       (denote-subdirectory-prompt)))
'''

Results in: "/home/peter/org/zk/biblio"

The `expand-file-name` function ensures that slashes are removed or added when needed. When denote-directory is not a string, it will ask for an existing subdir.

**Comment by pprevos** [comment]
I am glad we got there in the end :)

Committed: [ee33058](https://github.com/pprevos/citar-denote/commit/ee33058fbce47b9874af6928b202223e6b12700b)
